embedding_model: "BAAI/bge-small-zh-v1.5"
reranker_model:  "BAAI/bge-reranker-v2-m3"
llm_model:       "Qwen/Qwen2.5-0.5B-Instruct"
chunk_size: 800
chunk_overlap: 200
rrf_k: 60
retrieval_topk: 20
rerank_topk: 8
final_context_k: 5
