# UV Python version
python-version = "3.11"

# UV specific configuration
[tool.uv]
dev-dependencies = [
    "ruff>=0.4.0",
    "black>=24.0",
    "isort>=5.13", 
    "mypy>=1.10",
    "pytest>=8.0",
    "pytest-cov>=5.0",
    "pre-commit>=3.7",
]
